import datetime

datumi_vardi = {

    # Janvāris

    (1, 1): {"vārdi": ["Laimnesis", "Solvita", "Solvija"]},
    (1, 2): {"vārdi": ["Indulis", "Iva", "Ivis", "Ivo"]},
    (1, 3): {"vārdi": ["Miervalda", "Miervaldis"]},
    (1, 4): {"vārdi": ["Ilva", "Spodra"]},
    (1, 5): {"vārdi": ["Sīmanis", "Zintis"]},
    (1, 6): {"vārdi": ["Arnita", "Spulga"]},
    (1, 7): {"vārdi": ["Digmārs", "Juliāns", "Rota", "Zigmārs"]},
    (1, 8): {"vārdi": ["Gatis", "Ivanda"]},
    (1, 9): {"vārdi": ["Aksels", "Alta", "Kaspars"]},
    (1, 10): {"vārdi": ["Ringolds", "Dorisa", "Tatjana"]},
    (1, 11): {"vārdi": ["Franciska", "Smaida"]},
    (1, 12): {"vārdi": ["Reina", "Reinholds", "Reinis", "Renāts"]},
    (1, 13): {"vārdi": ["Aira", "Ārijs", "Āris", "Harijs"]},
    (1, 14): {"vārdi": ["Raitis", "Raits", "Roberta", "Roberts"]},
    (1, 15): {"vārdi": ["Felicita", "Fēlikss"]},
    (1, 16): {"vārdi": ["Lida", "Lidija"]},
    (1, 17): {"vārdi": ["Dravs", "Tenis"]},
    (1, 18): {"vārdi": ["Anits", "Antons"]},
    (1, 19): {"vārdi": ["Alnis", "Andulis"]},
    (1, 20): {"vārdi": ["Alģis", "Aļģidrs", "Oļģerts", "Orests"]},
    (1, 21): {"vārdi": ["Agne", "Agnese", "Agnija"]},
    (1, 22): {"vārdi": ["Austris"]},
    (1, 23): {"vārdi": ["Grieta", "Strauta"]},
    (1, 24): {"vārdi": ["Eglons", "Krišs", "Ksenija", "Egle"]},
    (1, 25): {"vārdi": ["Sigudrs", "Zigurds"]},
    (1, 26): {"vārdi": ["Agneta", "Agnis", "Ansis"]},
    (1, 27): {"vārdi": ["Ildze", "Ilze", "Izolde"]},
    (1, 28): {"vārdi": ["Kārlis", "Spodris"]},
    (1, 29): {"vārdi": ["Aivars", "Valērijs"]},
    (1, 30): {"vārdi": ["Pārlsa", "Tīna", "Valentīna"]},
    (1, 31): {"vārdi": ["Tekla", "Violeta"]},

    # Februāris

    (2, 1): {"vārdi": ["Britiga", "Indars", "Indra", "Indris"]},
    (2, 2): {"vārdi": ["Sonora", "Spīdola"]},
    (2, 3): {"vārdi": ["Aīda", "Ida", "Vida"]},
    (2, 4): {"vārdi": ["Daile", "Veronika"]},
    (2, 5): {"vārdi": ["Agate", "Selga", "Silga", "Sinilga"]},
    (2, 6): {"vārdi": ["Dace", "Dārta", "Dora"]},
    (2, 7): {"vārdi": ["Nelda", "Ričards", "Rihards"]},
    (2, 8): {"vārdi": ["Aldona"]},
    (2, 9): {"vārdi": ["Apolonija", "Simona"]},
    (2, 10): {"vārdi": ["Paula", "Paulīne"]},
    (2, 11): {"vārdi": ["Laima", "Laimdota"]},
    (2, 12): {"vārdi": ["Karlīna", "Līna"]},
    (2, 13): {"vārdi": ["Malda", "Melita"]},
    (2, 14): {"vārdi": ["Valentīns"]},
    (2, 15): {"vārdi": ["Alozis", "Alvis", "Olafs", "Olavs"]},
    (2, 16): {"vārdi": ["Džuljete", "Jūlija"]},
    (2, 17): {"vārdi": ["Donats", "Konstance"]},
    (2, 18): {"vārdi": ["Kintija", "Kora"]},
    (2, 19): {"vārdi": ["Zane", "Zuzanna"]},
    (2, 20): {"vārdi": ["Smuidra", "Smuidris", "Vitauts"]},
    (2, 21): {"vārdi": ["Ariadne", "Eleanora"]},
    (2, 22): {"vārdi": ["Adrians", "Ārija", "Rigonda"]},
    (2, 23): {"vārdi": ["Almants", "Haralds"]},
    (2, 24): {"vārdi": ["Diāna", "Dina", "Dins"]},
    (2, 25): {"vārdi": ["Alma", "Annemarija"]},
    (2, 26): {"vārdi": ["Aurēlija", "Evelīna", "Mētra"]},
    (2, 27): {"vārdi": ["Andra", "Līva", "Līvija"]},
    (2, 28): {"vārdi": ["Justs", "Skaidra", "Skaidrīte"]},

    # Marts

    (3, 1): {"vārdi": ["Ilgvars", "Ivars"]},
    (3, 2): {"vārdi": ["Laila", "Lavīze", "Luīze"]},
    (3, 3): {"vārdi": ["Marts", "Tālavs", "Tālis"]},
    (3, 4): {"vārdi": ["Alise", "Auce", "Enija"]},
    (3, 5): {"vārdi": ["Aurora", "Austra"]},
    (3, 6): {"vārdi": ["Centis", "Gotfrīds", "Vents"]},
    (3, 7): {"vārdi": ["Ella", "Elmīra"]},
    (3, 8): {"vārdi": ["Dagmāra", "Marga", "Margrita"]},
    (3, 9): {"vārdi": ["Ēvalds"]},
    (3, 10): {"vārdi": ["Laimrota", "Liliāna", "Silvija"]},
    (3, 11): {"vārdi": ["Agita", "Konstantīns"]},
    (3, 12): {"vārdi": ["Aija", "Aiva"]},
    (3, 13): {"vārdi": ["Balvis", "Ernests"]},
    (3, 14): {"vārdi": ["Matilde", "Ulrika"]},
    (3, 15): {"vārdi": ["Amalda", "Amilda", "Imalda"]},
    (3, 16): {"vārdi": ["Guntas", "Guntis"]},
    (3, 17): {"vārdi": ["Gerda", "Gertrūde", "Ģertrūde"]},
    (3, 18): {"vārdi": ["Adelīna", "Ilona"]},
    (3, 19): {"vārdi": ["Jāzeps"]},
    (3, 20): {"vārdi": ["Irbe", "Made"]},
    (3, 21): {"vārdi": ["Benedikts", "Benedikts", "Dzelme", "Unda", "Unigunde"]},
    (3, 22): {"vārdi": ["Dziedra", "Tamāra"]},
    (3, 23): {"vārdi": ["Mirda", "Žanete", "Žanna"]},
    (3, 24): {"vārdi": ["Izidors", "Kazimirs"]},
    (3, 25): {"vārdi": ["Māra", "Marita", "Mārīte", "Mare"]},
    (3, 26): {"vārdi": ["Eiženija", "Ženija"]},
    (3, 27): {"vārdi": ["Gustavs", "Gusts", "Tālrīts"]},
    (3, 28): {"vārdi": ["Ginta", "Gunda", "Gunta"]},
    (3, 29): {"vārdi": ["Agija", "Aldonis"]},
    (3, 30): {"vārdi": ["Igmārs", "Ilgmārs", "Nanija"]},
    (3, 31): {"vārdi": ["Atvars", "Gvido"]},

    # Aprīlis

    (4, 1): {"vārdi": ["Dagne", "Dagnis"]},
    (4, 2): {"vārdi": ["Imgarde", "Irmgarde"]},
    (4, 3): {"vārdi": ["Daria", "Dairis", "Daiva"]},
    (4, 4): {"vārdi": ["Ārvalda", "Ārvalds", "Herta", "Valda"]},
    (4, 5): {"vārdi": ["Aivija", "Vidaga", "Vija"]},
    (4, 6): {"vārdi": ["Dzinta", "Filips", "Vīlips", "Zinta"]},
    (4, 7): {"vārdi": ["Helmuts", "Zina", "Zinaīda"]},
    (4, 8): {"vārdi": ["Dana", "Dans", "Danute", "Edgars"]},
    (4, 9): {"vārdi": ["Valrērija", "Žubīte"]},
    (4, 10): {"vārdi": ["Anita", "Anitra", "Zīle"]},
    (4, 11): {"vārdi": ["Hermanis", "Vilmārs"]},
    (4, 12): {"vārdi": ["Ainis", "Jūlijs"]},
    (4, 13): {"vārdi": ["Egils", "Egīls", "Nauris"]},
    (4, 14): {"vārdi": ["Gudrīte", "Strauja"]},
    (4, 15): {"vārdi": ["Aelita", "Gastons"]},
    (4, 16): {"vārdi": ["Alfs", "Bermadeta", "Mintauts"]},
    (4, 17): {"vārdi": ["Rūdis", "Rūdolfs", "Viviāna"]},
    (4, 18): {"vārdi": ["Jadviga", "Laura"]},
    (4, 19): {"vārdi": ["Fanija", "Vēsma"]},
    (4, 20): {"vārdi": ["Mirta", "Ziedīte"]},
    (4, 21): {"vārdi": ["Anastasija", "Marģers"]},
    (4, 22): {"vārdi": ["Armanda", "Armands"]},
    (4, 23): {"vārdi": ["Georgs", "Jurģis", "Juris"]},
    (4, 24): {"vārdi": ["Nameda", "Ritvaldis", "Visvaldis"]},
    (4, 25): {"vārdi": ["Bārbala", "Līksma"]},
    (4, 26): {"vārdi": ["Alīna", "Rūsiņš", "Sandris"]},
    (4, 27): {"vārdi": ["Klementīne", "Raimonds", "Raina", "Tāle"]},
    (4, 28): {"vārdi": ["Gundega", "Terēze"]},
    (4, 29): {"vārdi": ["Liene", "Raimonds", "Vilnis"]},
    (4, 30): {"vārdi": ["Alta", "Liāna", "Lilija"]},

    # Maijs

    (5, 1): {"vārdi": ["Ziedonis"]},
    (5, 2): {"vārdi": ["Sigmunds", "Zigismunds"]},
    (5, 3): {"vārdi": ["Gints", "Uvis"]},
    (5, 4): {"vārdi": ["Vijolīte", "Viola", "Vizbulīte"]},
    (5, 5): {"vārdi": ["Ģederts", "Ģirts"]},
    (5, 6): {"vārdi": ["Didzis", "Gaidis"]},
    (5, 7): {"vārdi": ["Henriete", "Henrijs", "Jete", "Enriko"]},
    (5, 8): {"vārdi": ["Staņislava", "Staņislavs", "Stefānija"]},
    (5, 9): {"vārdi": ["Zigmunds", "Einārs", "Ervīns", "Klāvs"]},
    (5, 10): {"vārdi": ["Maija", "Paija"]},
    (5, 11): {"vārdi": ["Karmena", "Manfreds", "Milda"]},
    (5, 12): {"vārdi": ["Ina", "Ināra", "Inārs", "Valija"]},
    (5, 13): {"vārdi": ["Ira", "Iraīda", "Irēna", "Irina"]},
    (5, 14): {"vārdi": ["Aivis", "Elfa", "Elvita", "Krišjānis"]},
    (5, 15): {"vārdi": ["Airita", "Arita", "Sofija", "Taiga"]},
    (5, 16): {"vārdi": ["Edijs", "Edvīns"]},
    (5, 17): {"vārdi": ["Dailis", "Herberts", "Umberts"]},
    (5, 18): {"vārdi": ["Ēriks", "Inese", "Inesis"]},
    (5, 19): {"vārdi": ["Lita", "Sibila", "Teika"]},
    (5, 20): {"vārdi": ["Salvis", "Selva", "Venta"]},
    (5, 21): {"vārdi": ["Akvelīna", "Ernestīne", "Igmārs"]},
    (5, 22): {"vārdi": ["Emīlija"]},
    (5, 23): {"vārdi": ["Leokādija", "Leonīte", "Ligija", "Lonija"]},
    (5, 24): {"vārdi": ["Ilvija", "Merlēna", "Ziedone"]},
    (5, 25): {"vārdi": ["Anšlavs", "Junora"]},
    (5, 26): {"vārdi": ["Eduards", "Edvards", "Varis"]},
    (5, 27): {"vārdi": ["Dzidra", "Dzidris", "Gunita", "Loreta"]},
    (5, 28): {"vārdi": ["Vilhelms", "Vilis"]},
    (5, 29): {"vārdi": ["Maksis", "Raivis", "Ralvo"]},
    (5, 30): {"vārdi": ["Lolita", "Vitolds"]},
    (5, 31): {"vārdi": ["Alīda", "Jūsma"]},

    # Jūnijs

    (6, 1): {"vārdi": ["Bernedīne", "Biruta", "Mairita"]},
    (6, 2): {"vārdi": ["Emma", "Lība"]},
    (6, 3): {"vārdi": ["Ineta", "Inta", "Intra"]},
    (6, 4): {"vārdi": ["Elfrīda", "Sindija", "Sintija"]},
    (6, 5): {"vārdi": ["Igors", "Igvars", "Margots"]},
    (6, 6): {"vārdi": ["Ardis", "Ingrīda"]},
    (6, 7): {"vārdi": ["Arnis", "Gaida"]},
    (6, 8): {"vārdi": ["Frīda", "Frīdis", "Mundra"]},
    (6, 9): {"vārdi": ["Gita", "Ligita"]},
    (6, 10): {"vārdi": ["Anatols", "Malva"]},
    (6, 11): {"vārdi": ["Ingus", "Mairis", "Vidvuds"]},
    (6, 12): {"vārdi": ["Ija", "Leonora", "Nora"]},
    (6, 13): {"vārdi": ["Ainārs", "Uva", "Zigfrīds"]},
    (6, 14): {"vārdi": ["Saiva", "Saivis", "Santis", "Sentis", "Tija"]},
    (6, 15): {"vārdi": ["Baņuta", "Villija", "Vīts", "Žermēna"]},
    (6, 16): {"vārdi": ["Justīne", "Juta"]},
    (6, 17): {"vārdi": ["Artis", "Artūrs"]},
    (6, 18): {"vārdi": ["Alberts", "Madis"]},
    (6, 19): {"vārdi": ["Nils", "Viktors"]},
    (6, 20): {"vārdi": ["Maira", "Rasa", "Rasma"]},
    (6, 21): {"vārdi": ["Egita", "Emīls", "Monvīds"]},
    (6, 22): {"vārdi": ["Laimdots", "Laimiņš", "Ludmila"]},
    (6, 23): {"vārdi": ["Līga"]},
    (6, 24): {"vārdi": ["Jānis"]},
    (6, 25): {"vārdi": ["Maiga", "Milija"]},
    (6, 26): {"vārdi": ["Ausma", "Ausmis", "Inguna", "Inguns"]},
    (6, 27): {"vārdi": ["Malvīne", "Malvis"]},
    (6, 28): {"vārdi": ["Kitija", "Viestards", "Viesturs"]},
    (6, 29): {"vārdi": ["Paulis", "Pauls", "Pāvils", "Pēteris"]},
    (6, 30): {"vārdi": ["Mareks", "Tālivaldis"]},

    # Jūlijs

    (7, 1): {"vārdi": ["Imants", "Ingars", "Intars", "Rimants"]},
    (7, 2): {"vārdi": ["Halina", "Ilvars", "Lauma"]},
    (7, 3): {"vārdi": ["Benita", "Everita", "Verita"]},
    (7, 4): {"vārdi": ["Sandis", "Uldis", "Ulvis"]},
    (7, 5): {"vārdi": ["Andžejs", "Andžs", "Edīte", "Esmerelda"]},
    (7, 6): {"vārdi": ["Anrijs", "Arkādijs"]},
    (7, 7): {"vārdi": ["Alda", "Maruta"]},
    (7, 8): {"vārdi": ["Ada", "Adele", "Antra"]},
    (7, 9): {"vārdi": ["Asna", "Asne", "Zaiga"]},
    (7, 10): {"vārdi": ["Lija", "Olīvija"]},
    (7, 11): {"vārdi": ["Leonora", "Svens"]},
    (7, 12): {"vārdi": ["Indriķis", "Ints", "Namejs"]},
    (7, 13): {"vārdi": ["Margarita", "Margrieta"]},
    (7, 14): {"vārdi": ["Anvars", "Oskars", "Ritvars"]},
    (7, 15): {"vārdi": ["Egija", "Egmonts", "Egons", "Henrihs", "Henriks"]},
    (7, 16): {"vārdi": ["Estere", "Hermīne", "Liepa"]},
    (7, 17): {"vārdi": ["Aleksejs", "Aleksis"]},
    (7, 18): {"vārdi": ["Rozālija", "Roze"]},
    (7, 19): {"vārdi": ["Digna", "Jautrīte", "Kamila"]},
    (7, 20): {"vārdi": ["Ramona", "Ritma"]},
    (7, 21): {"vārdi": ["Meldra", "Meldris", "Melisa"]},
    (7, 22): {"vārdi": ["Marija", "Marika", "Mariana"]},
    (7, 23): {"vārdi": ["Magda", "Magone", "Mērija"]},
    (7, 24): {"vārdi": ["Krista", "Kristiāna", "Kristiāns", "Kristīne"]},
    (7, 25): {"vārdi": ["Jēkabs", "Žaklīna"]},
    (7, 26): {"vārdi": ["Ance", "Anna", "Annija"]},
    (7, 27): {"vārdi": ["Dita", "Marta"]},
    (7, 28): {"vārdi": ["Cecīlija", "Cilda"]},
    (7, 29): {"vārdi": ["Edmunds", "Edžus", "Vildmants"]},
    (7, 30): {"vārdi": ["Renārs", "Valters"]},
    (7, 31): {"vārdi": ["Angelika", "Ruta", "Rūta", "Sigita"]},   

    # Augusts

    (8, 1): {"vārdi": ["Albīna", "Albīns"]},
    (8, 2): {"vārdi": ["Normunds", "Stefans"]},
    (8, 3): {"vārdi": ["Augusts"]},
    (8, 4): {"vārdi": ["Romānds", "Romualda", "Romualds"]},
    (8, 5): {"vārdi": ["Arvils", "Osvalds"]},
    (8, 6): {"vārdi": ["Aisma", "Askolds"]},
    (8, 7): {"vārdi": ["Alfrēds", "Fredis", "Madars"]},
    (8, 8): {"vārdi": ["Mudīta", "Vladislava", "Vladislavs"]},
    (8, 9): {"vārdi": ["Genoveva", "Madara"]},
    (8, 10): {"vārdi": ["Audris", "Brencis", "Inuta"]},
    (8, 11): {"vārdi": ["Liega", "Olga", "Zigita", "Zita"]},
    (8, 12): {"vārdi": ["Klāra", "Vizma"]},
    (8, 13): {"vārdi": ["Elvīra", "Velga"]},
    (8, 14): {"vārdi": ["Virma", "Zelma", "Zemgus"]},
    (8, 15): {"vārdi": ["Dzelde", "Zelda", "Zenta"]},
    (8, 16): {"vārdi": ["Astra", "Astrīda"]},
    (8, 17): {"vārdi": ["Oļegs", "Vineta"]},
    (8, 18): {"vārdi": ["Elena", "Ellena", "Helēna", "Liena", "Liene"]},
    (8, 19): {"vārdi": ["Imanta", "Melānija"]},
    (8, 20): {"vārdi": ["Bermhards", "Boriss"]},
    (8, 21): {"vārdi": ["Janīna", "Linda"]},
    (8, 22): {"vārdi": ["Everts", "Rudīte"]},
    (8, 23): {"vārdi": ["Ralfs", "Valgudis", "Vitālijs"]},
    (8, 24): {"vārdi": ["Bērtulis", "Boļeslavs"]},
    (8, 25): {"vārdi": ["Ivonna", "Ludis", "Ludvigs", "Patrīcija"]},
    (8, 26): {"vārdi": ["Broņislava", "Broņislavs", "Natālija", "Tālija"]},
    (8, 27): {"vārdi": ["Alens", "Jorens", "Žanis"]},
    (8, 28): {"vārdi": ["Auguste", "Guste"]},
    (8, 29): {"vārdi": ["Aiga", "Armīns", "Vismants"]},
    (8, 30): {"vārdi": ["Alvis", "Jolanta", "Samanta"]},
    (8, 31): {"vārdi": ["Aigars", "Vilma"]},

    # Septembris

    (9, 1): {"vārdi": ["Austrums", "Ilmārs", "Iluta"]},
    (9, 2): {"vārdi": ["Elīza", "Lizeta", "Zete"]},
    (9, 3): {"vārdi": ["Bella", "Berta"]},
    (9, 4): {"vārdi": ["Dzintara", "Dzintars", "Dzintra"]},
    (9, 5): {"vārdi": ["Klaudija", "Persijs", "Vaida"]},
    (9, 6): {"vārdi": ["Magnuss", "Maigonis", "Mauriuss"]},
    (9, 7): {"vārdi": ["Ermīns", "Regīna"]},
    (9, 8): {"vārdi": ["Ilga"]},
    (9, 9): {"vārdi": ["Bruno", "Telma"]},
    (9, 10): {"vārdi": ["Albertīne", "Jausma"]},
    (9, 11): {"vārdi": ["Signe", "Signija"]},
    (9, 12): {"vārdi": ["Erna", "Eva", "Evita"]},
    (9, 13): {"vārdi": ["Iza", "Izabella"]},
    (9, 14): {"vārdi": ["Sanda", "Sanija", "Sanita", "Santa"]},
    (9, 15): {"vārdi": ["Gunvaldis", "Gunvaris", "Sandra", "Sondra"]},
    (9, 16): {"vārdi": ["Asja","Asnate", "Dāgs", "Dārgs"]},
    (9, 17): {"vārdi": ["Vaira", "Vairis", "Vera"]},
    (9, 18): {"vārdi": ["Alita", "Elita", "Liesma"]},
    (9, 19): {"vārdi": ["Muntis", "Verners"]},
    (9, 20): {"vārdi": ["Ginters", "Guntra", "Marianna"]},
    (9, 21): {"vārdi": ["Mariss", "Matīss", "Modris"]},
    (9, 22): {"vārdi": ["Maiguts", "Mārica", "Māris"]},
    (9, 23): {"vārdi": ["Vanda", "Venerada", "Venija"]},
    (9, 24): {"vārdi": ["Agris", "Agrita"]},
    (9, 25): {"vārdi": ["Rauls", "Rodrigo"]},
    (9, 26): {"vārdi": ["Gundats", "Knuts", "Kurts"]},
    (9, 27): {"vārdi": ["Ādolfs", "Ilgonis"]},
    (9, 28): {"vārdi": ["Lana", "Sergejs", "Svetlana"]},
    (9, 29): {"vārdi": ["Milģelis", "Mihails", "Miks", "Mikus", "Miķelis"]},
    (9, 30): {"vārdi": ["Elma", "Elna", "Menarda"]},

    # Oktobris

    (10, 1): {"vārdi": ["Lāsma", "Zanda", "Zandis"]},
    (10, 2): {"vārdi": ["Ilma", "Skaidris"]},
    (10, 3): {"vārdi": ["Elza", "Ilizana"]},
    (10, 4): {"vārdi": ["Francis", "Modra", "Dimitrijs"]},
    (10, 5): {"vārdi": ["Amālija"]},
    (10, 6): {"vārdi": ["Monika", "Zilga", "Zilgma"]},
    (10, 7): {"vārdi": ["Daumants", "Druvvaldis"]},
    (10, 8): {"vārdi": ["Aina", "Anete"]},
    (10, 9): {"vārdi": ["Elga", "Elgars", "Helga"]},
    (10, 10): {"vārdi": ["Arvīds", "Arvis", "Druvis"]},
    (10, 11): {"vārdi": ["Monta", "Silva", "Tince"]},
    (10, 12): {"vārdi": ["Kira", "Valfrīds"]},
    (10, 13): {"vārdi": ["Irma", "Mirga"]},
    (10, 14): {"vārdi": ["Minna", "Vilhelmīne"]},
    (10, 15): {"vārdi": ["Eda", "Hedriva", "Helvija"]},
    (10, 16): {"vārdi": ["Daiga", "Dinija"]},
    (10, 17): {"vārdi": ["Gaits", "Karīna"]},
    (10, 18): {"vārdi": ["Erlends", "Rolanda", "Rolands", "Ronalds", "Lūkass"]},
    (10, 19): {"vārdi": ["Drosma", "Drosmis", "Elīna"]},
    (10, 20): {"vārdi": ["Leonīda", "Leonīds"]},
    (10, 21): {"vārdi": ["Severīns", "Urzula"]},
    (10, 22): {"vārdi": ["Irīda", "Īrisa"]},
    (10, 23): {"vārdi": ["Daina", "Dainida", "Dainis"]},
    (10, 24): {"vārdi": ["Modrīte", "Mudrīte", "Renāte"]},
    (10, 25): {"vārdi": ["Beāte", "Beatrise"]},
    (10, 26): {"vārdi": ["Amanda", "Amanta", "Kaiva"]},
    (10, 27): {"vārdi": ["Irita", "Ita", "Lilita"]},
    (10, 28): {"vārdi": ["Antoņina", "Ninona", "Ņina", "Oksana"]},
    (10, 29): {"vārdi": ["Elva", "Elvijs", "Elvis", "Laims", "Laimonis"]},
    (10, 30): {"vārdi": ["Nadīna", "Ulla"]},
    (10, 31): {"vārdi": ["Rinalda", "Rinalds", "Valts"]},

    # Novembris

    (11, 1): {"vārdi": ["Ikars"]},
    (11, 2): {"vārdi": ["Dzīle", "Viva", "Vivita"]},
    (11, 3): {"vārdi": ["Dagnija", "Ērika"]},
    (11, 4): {"vārdi": ["Atis", "Oto", "Otomārs"]},
    (11, 5): {"vārdi": ["Lote", "Šarlote"]},
    (11, 6): {"vārdi": ["Leo", "Leonards", "Leons", "Linards"]},
    (11, 7): {"vārdi": ["Helma", "Lotārs"]},
    (11, 8): {"vārdi": ["Agra", "Aleksandra"]},
    (11, 9): {"vārdi": ["Teodors"]},
    (11, 10): {"vārdi": ["Mārcis", "Markuss", "Mārtiņš"]},
    (11, 11): {"vārdi": ["Nellija", "Ojārs", "Rainers"]},
    (11, 12): {"vārdi": ["Kaija", "Kornēlija"]},
    (11, 13): {"vārdi": ["Eižens", "Jevgēņija", "Jevgēnijs"]},
    (11, 14): {"vārdi": ["Fricis", "Vikentijs"]},
    (11, 15): {"vārdi": ["Leopolds", "Unda", "Undīne"]},
    (11, 16): {"vārdi": ["Banga", "Glorija"]},
    (11, 17): {"vārdi": ["Hugo", "Uga", "Uģis"]},
    (11, 18): {"vārdi": ["Brīve", "Aleksandrs", "Doloresa"]},
    (11, 19): {"vārdi": ["Betija", "Elizabete", "Liza", "Līze"]},
    (11, 20): {"vārdi": ["Anda", "Andīna", "Vigo"]},
    (11, 21): {"vārdi": ["Andis", "Zeltīte"]},
    (11, 22): {"vārdi": ["Aldis", "Aldris", "Alfons"]},
    (11, 23): {"vārdi": ["Zigrīda", "Zigrīda", "Zigrīds"]},
    (11, 24): {"vārdi": ["Velda", "Velta"]},
    (11, 25): {"vārdi": ["Kadrija", "Kate", "Katrīna", "Trīne"]},
    (11, 26): {"vārdi": ["Konrāds", "Sebastians", "Sebastijans"]},
    (11, 27): {"vārdi": ["Lauris", "Norberts"]},
    (11, 28): {"vārdi": ["Olita", "Rita", "Vita"]},
    (11, 29): {"vārdi": ["Igants", "Virgīnija"]},
    (11, 30): {"vārdi": ["Andrejs", "Andreivs", "Andris"]},

    # Decembris

    (12, 1): {"vārdi": ["Arnolds", "Emanuels"]},
    (12, 2): {"vārdi": ["Meta", "Sniedze"]},
    (12, 3): {"vārdi": ["Evija", "Jogita", "Raita"]},
    (12, 4): {"vārdi": ["Baiba", "Barba", "Barbara"]},
    (12, 5): {"vārdi": ["Klaudijs", "Sabīne", "Sarma"]},
    (12, 6): {"vārdi": ["Niklāvs", "Nikolajs", "Niks"]},
    (12, 7): {"vārdi": ["Anta", "Antonija", "Dzirkstīte"]},
    (12, 8): {"vārdi": ["Gunārs", "Gunis", "Vladimirs"]},
    (12, 9): {"vārdi": ["Sarmīte", "Tabita"]},
    (12, 10): {"vārdi": ["Guna", "Judīte"]},
    (12, 11): {"vārdi": ["Valdemārs", "Valdis", "Voldemārs"]},
    (12, 12): {"vārdi": ["Oveta", "Otīlija"]},
    (12, 13): {"vārdi": ["Lūcija", "Veldze"]},
    (12, 14): {"vārdi": ["Auseklis", "Gaisma"]},
    (12, 15): {"vārdi": ["Hanna", "Jana", "Joganna"]},
    (12, 16): {"vārdi": ["Alvīne"]},
    (12, 17): {"vārdi": ["Hilda", "Teiksma"]},
    (12, 18): {"vārdi": ["Klinta", "Kristaps", "Kristofers", "Krists"]},
    (12, 19): {"vārdi": ["Lelde", "Sarmis"]},
    (12, 20): {"vārdi": ["Arta", "Minjona"]},
    (12, 21): {"vārdi": ["Sualcerīte", "Tomass", "Toms"]},
    (12, 22): {"vārdi": ["Saulvedis"]},
    (12, 23): {"vārdi": ["Balva", "Viktorija"]},
    (12, 24): {"vārdi": ["Ādams", "Ieva"]},
    (12, 25): {"vārdi": ["Larisa", "Stella"]},
    (12, 26): {"vārdi": ["Dainuvīte", "Gija", "Megija"]},
    (12, 27): {"vārdi": ["Elmārs", "Inita"]},
    (12, 28): {"vārdi": ["Inga", "Ingeborga", "Irvita", "Ivita"]},
    (12, 29): {"vārdi": ["Ilgona", "Solveiga"]},
    (12, 30): {"vārdi": ["Daniela", "Dāniels", "Dāvids", "Dāvis"]},
    (12, 31): {"vārdi": ["Kalvis", "Silvestrs", "Silvis"]},
}

today = datetime.date.today()
key = (today.month, today.day)

if key in datumi_vardi:
    names = datumi_vardi[key]["vārdi"]
    print(f"{today} vārda dienas svin: ", ", ".join(names))
else:
    print("Šodien nav nevienam vārda dienas?")
